import { readFile, writeFile, mkdir, realpath, stat, rename, rm, mkdtemp } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { basename, dirname, extname, join, relative, resolve, sep } from 'node:path';
import { createHash } from 'node:crypto';
import { loadRuntime } from './runtime.ts';
import { scan, documentProps, type Ref } from './scan.ts';
import { validateManifest } from './manifest.ts';

const flags=new Map<string,string>();
for(let i=2;i<process.argv.length;i++) {const key=process.argv[i];flags.set(key,key==='--force'?'true':process.argv[++i]);}
const required=(key:string)=>{const value=flags.get(key);if(!value)throw new Error(`Missing ${key}`);return value;};
const json=(data:any)=>JSON.stringify(data,null,2)+'\n';
const slash=(p:string)=>p.split(sep).join('/');
const localImport=(from:string,to:string)=>{const p=slash(relative(dirname(from),to));return p.startsWith('.')?p:'./'+p;};
async function packageRoot(file:string) {let dir=dirname(file);while(!existsSync(join(dir,'package.json'))){const parent=dirname(dir);if(parent===dir)throw new Error(`No package.json found above ${file}`);dir=parent;}return dir;}
async function packageVersion(file:string,name:string) {let dir=dirname(file);while(true){try{const p=JSON.parse(await readFile(join(dir,'package.json'),'utf8'));const version=p.dependencies?.[name]??p.devDependencies?.[name]??p.peerDependencies?.[name];if(version)return version;}catch{}const parent=dirname(dir);if(parent===dir)break;dir=parent;}throw new Error(`Package ${name} is not declared in the source project. Add it to package.json before importing.`);}
const packageName=(s:string)=>s.startsWith('@')?s.split('/').slice(0,2).join('/'):s.split('/')[0];
const ignored=(s:string)=>/^(https?:|data:|blob:|\/\/)/.test(s);

async function main() {
 const origin=await realpath(resolve(required('--origin')));const target=await realpath(resolve(required('--target')));
 const framework=required('--framework');const name=required('--name');
 if(!['react','vue','svelte','solid'].includes(framework)||!(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).test(name))throw new Error('Invalid framework or component slug.');
 const ext=extname(origin);if(!(framework==='vue'?ext==='.vue':framework==='svelte'?ext==='.svelte':/\.[jt]sx$/.test(ext)))throw new Error(`Expected a ${framework} component file, received ${ext}.`);
 const targetPackage=JSON.parse(await readFile(join(target,'package.json'),'utf8'));
 if(!flags.has('--runtime')&&!existsSync(join(target,'src/components/ComponentPage.astro')))throw new Error('Target is not a Kuit viewer. Start with the included site/ template.');
 const destination=join(target,framework,name);const pageDir=join(target,'src/pages','components',framework,name);
 // Resolve parent symlinks before any writes: bundles and generated routes must stay in the viewer.
 for(const dir of [destination,pageDir]) {let existing=dir;while(!existsSync(existing))existing=dirname(existing);const actual=await realpath(existing);if(actual!==target&&!actual.startsWith(target+sep))throw new Error(`Destination escapes the viewer through a symlink: ${dir}`);}
 if(origin===destination||origin.startsWith(destination+sep))throw new Error('Cannot import from the bundle being replaced.');
 for(const path of [destination,pageDir])if(existsSync(path)) {
  if(!flags.has('--force'))throw new Error(`${path} already exists. Use --force to replace a generated bundle.`);
  if(path===destination&&!existsSync(join(path,'kuit.json')))throw new Error('Refusing to replace a folder without kuit.json.');
  if(path===pageDir&&!(await readFile(join(path,'index.astro'),'utf8')).includes('Generated by kuit'))throw new Error('Refusing to replace a page not generated by kuit.');
 }
 const runtime=await loadRuntime(flags.get('--runtime')??target);const root=await packageRoot(origin);
 const server=await runtime.vite.createServer({root,server:{middlewareMode:true,hmr:false,ws:false,watch:null},appType:'custom',logLevel:'error',optimizeDeps:{noDiscovery:true,include:[]}});
 const files=new Map<string,{name:string,code?:string,refs:Ref[],edits:{start:number,end:number,text:string}[]}>();
 const used=new Set(['kuit.json','preview-props.json']);const dependencies:Record<string,string>={};
 const compilerOptions=(()=>{const config=runtime.ts.findConfigFile(root,runtime.ts.sys.fileExists);if(!config)return {};const read=runtime.ts.readConfigFile(config,runtime.ts.sys.readFile);return runtime.ts.parseJsonConfigFileContent(read.config,runtime.ts.sys,dirname(config)).options;})();
 let entryScripts:any[]=[];
 async function dependency(ref:Ref,importer:string):Promise<{path?:string,suffix?:string}> {
  const spec=ref.value;if(ignored(spec)||(ref.kind==='asset'&&spec.startsWith('#')))return {};
  if(spec.startsWith('node:')||spec.startsWith('bun:'))throw new Error(`Server-only import ${spec} cannot run in a browser preview.`);
  const split=spec.startsWith('#')?spec.indexOf('?'):spec.search(/[?#]/);const clean=split<0?spec:spec.slice(0,split);const suffix=split<0?'':spec.slice(split);
  const isRelative=clean.startsWith('.');const isRoot=clean.startsWith('/');
  let resolved:any;
  try{resolved=await server.pluginContainer.resolveId(clean,importer);}catch{}
  let path=resolved?.id?.split('?')[0];
  if(path?.startsWith('\0')||resolved?.external)throw new Error(`Virtual/external module ${spec} needs a project-specific adapter.`);
  if(!path||!existsSync(path)) {
   const resolvedTS=runtime.ts.resolveModuleName(clean,importer,compilerOptions,runtime.ts.sys).resolvedModule;
   if(resolvedTS&&!resolvedTS.isExternalLibraryImport)path=resolvedTS.resolvedFileName;
   else if(isRelative||ref.kind==='asset')path=resolve(dirname(importer),clean);
   if(isRoot)path=join(root,'public',clean.slice(1));
  }
  if(path&&existsSync(path)&&!path.includes(`${sep}node_modules${sep}`))return {path:await realpath(path),suffix};
  if(!isRelative&&!isRoot&&ref.kind==='module') {
   const pkg=packageName(clean);const version=await packageVersion(importer,pkg);
   if(/^(workspace:|file:|link:)/.test(version))throw new Error(`Local package ${pkg} (${version}) cannot be installed in the viewer. Use a relative source import or publish the package.`);
   if(dependencies[pkg]&&dependencies[pkg]!==version)throw new Error(`Conflicting source versions for ${pkg}.`);
   dependencies[pkg]=version;return {};
  }
  throw new Error(`Cannot resolve ${spec} imported by ${importer}`);
 }
 async function visit(path:string,entry=false) {
  if(files.has(path))return files.get(path)!.name;
  if(!(await stat(path)).isFile())throw new Error(`Expected file: ${path}`);
  let output=entry?name+ext:basename(path).replace(/[^a-zA-Z0-9_.-]/g,'-');if(used.has(output.toLowerCase())){const e=extname(output);output=basename(output,e)+'-'+createHash('sha256').update(slash(relative(root,path))).digest('hex').slice(0,8)+e;}
  if(used.has(output.toLowerCase()))throw new Error(`Filename collision: ${output}`);used.add(output.toLowerCase());
  const item={name:output,refs:[] as Ref[],edits:[] as {start:number,end:number,text:string}[],code:undefined as string|undefined};files.set(path,item);
  if(/\.(?:[cm]?[jt]sx?|vue|svelte|css|scss|sass|less)$/.test(path)) {
   item.code=await readFile(path,'utf8');const parsed=scan(item.code,path,runtime);item.refs=parsed.refs;if(entry)entryScripts=parsed.scripts;
   const assetImports:string[]=[];
   for(const ref of item.refs) {
    const d=await dependency(ref,path);if(!d.path)continue;const child=await visit(d.path);const specifier='./'+child+(d.suffix??'');
    let text=specifier;
    if(ref.attribute){let identifier=`__kuitAsset${assetImports.length}`;while(item.code.includes(identifier))identifier+='_';assetImports.push(`import ${identifier} from ${JSON.stringify(specifier)};`);text=`${ref.attribute}={${identifier}}`;}
    item.edits.push({start:ref.start,end:ref.end,text});
   }
   if(assetImports.length){const imports='\n'+assetImports.join('\n')+'\n';const offset=parsed.scriptOffset??0;item.edits.push({start:offset,end:offset,text:parsed.scriptOffset===undefined?`<script>${imports}</script>\n`:imports});}
  }
  return output;
 }
 try{await visit(origin,true);}finally{await server.close();}
 let exportName=flags.get('--export');
 if(exportName&&!/^[A-Za-z_$][\w$]*$/.test(exportName))throw new Error('Invalid export name.');
 if(!['vue','svelte'].includes(framework)) {
  const ts=runtime.ts;const named=new Set<string>();let hasDefault=false;
  for(const sf of entryScripts)for(const n of sf.statements) {
   if(ts.isExportAssignment(n)||n.modifiers?.some((m:any)=>m.kind===ts.SyntaxKind.DefaultKeyword))hasDefault=true;
   if(n.modifiers?.some((m:any)=>m.kind===ts.SyntaxKind.ExportKeyword)) {
    if(n.name&&!ts.isInterfaceDeclaration(n)&&!ts.isTypeAliasDeclaration(n))named.add(n.name.text);
    if(ts.isVariableStatement(n))for(const d of n.declarationList.declarations)named.add(d.name.getText());
   }
   if(ts.isExportDeclaration(n)&&!n.isTypeOnly&&n.exportClause?.elements)for(const e of n.exportClause.elements){if(e.isTypeOnly)continue;if(e.name.text==='default')hasDefault=true;else named.add(e.name.text);}
  }
  if(exportName&&exportName!=='default'&&!named.has(exportName))throw new Error(`Export ${exportName} was not found.`);
  if(exportName==='default'&&!hasDefault)throw new Error('Export default was not found.');
  if(!exportName){const candidates=[...named].filter(n=>/^[A-Z]/.test(n));if(hasDefault)exportName='default';else if(candidates.length===1)exportName=candidates[0];else throw new Error('Choose the component export with --export Name (or provide a default export).');}
 } else exportName='default';
 const previewProps=flags.has('--props')?JSON.parse(required('--props')):{};
 if(!previewProps||typeof previewProps!=='object'||Array.isArray(previewProps))throw new Error('--props must be a JSON object.');
 const meta={schemaVersion:1,name,framework,entry:files.get(origin)!.name,export:exportName,files:[...files.values()].map(f=>f.name),dependencies,props:documentProps(entryScripts,runtime.ts,exportName)};
 const nextPackage=structuredClone(targetPackage);nextPackage.dependencies??={};const warnings:string[]=[];
 for(const [pkg,version]of Object.entries(dependencies)) {const existing=nextPackage.dependencies[pkg]??nextPackage.devDependencies?.[pkg];if(existing&&existing!==version)warnings.push(`${pkg}: source requests ${version}; keeping viewer version ${existing}.`);else if(!existing)nextPackage.dependencies[pkg]=version;}
 const staging=await mkdtemp(join(target,'.kuit-'));const stagedBundle=join(staging,'bundle');const stagedPages=join(staging,'pages');
 const moved:{dest:string,backup:string,existed:boolean,published:boolean}[]=[];
 try {
  await mkdir(stagedBundle);await mkdir(stagedPages);
  for(const [path,item]of files) {let content:string|Buffer;if(item.code!==undefined){content=item.code;for(const edit of item.edits.sort((a,b)=>b.start-a.start))content=content.slice(0,edit.start)+edit.text+content.slice(edit.end);}else content=await readFile(path);await writeFile(join(stagedBundle,item.name),content);}
  await validateManifest(meta, stagedBundle);
  await writeFile(join(stagedBundle,'kuit.json'),json(meta));await writeFile(join(stagedBundle,'preview-props.json'),json(previewProps));
  const docFile=join(pageDir,'index.astro');const previewFile=join(pageDir,'preview.astro');
  await writeFile(join(stagedPages,'index.astro'),`---\n// Generated by kuit\nimport ComponentPage from ${JSON.stringify(localImport(docFile,join(target,'src/components/ComponentPage.astro')))};\nimport meta from ${JSON.stringify(localImport(docFile,join(destination,'kuit.json')))};\n---\n<ComponentPage meta={meta} />\n`);
  const componentImport=JSON.stringify(localImport(previewFile,join(destination,meta.entry)));
  const importStatement=exportName==='default'?`import Component from ${componentImport};`:`import { ${exportName} as Component } from ${componentImport};`;
  await writeFile(join(stagedPages,'preview.astro'),`---\n// Generated by kuit. Customize this wrapper for providers or complex props.\n${importStatement}\nimport props from ${JSON.stringify(localImport(previewFile,join(destination,'preview-props.json')))};\nimport ${JSON.stringify(localImport(previewFile,join(target,'src/styles/preview.css')))};\n---\n<html lang="en" class="dark min-h-dvh bg-card font-sans text-foreground [color-scheme:dark]"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" /><title>${name} preview</title></head><body class="min-h-dvh bg-card"><main class="flex min-h-dvh items-center justify-center p-8"><Component {...props} client:only="${framework==='solid'?'solid-js':framework}" /></main></body></html>\n`);
  await writeFile(join(staging,'package.json'),json(nextPackage));
  for(const [source,dest]of [[stagedBundle,destination],[stagedPages,pageDir],[join(staging,'package.json'),join(target,'package.json')]]) {
   await mkdir(dirname(dest),{recursive:true});const record={dest,backup:join(staging,`backup-${moved.length}`),existed:existsSync(dest),published:false};moved.push(record);
   if(record.existed)await rename(dest,record.backup);await rename(source,dest);record.published=true;
  }
 }catch(error){for(const r of moved.reverse()){if(r.published)await rm(r.dest,{recursive:true,force:true});if(r.existed&&existsSync(r.backup))await rename(r.backup,r.dest);}throw error;}
 finally{await rm(staging,{recursive:true,force:true});}
 console.log(`Imported ${framework}/${name}: ${files.size} files\nRoute: /components/${framework}/${name}\nFolder: ${destination}`);
 for(const warning of warnings)console.warn(`Note: ${warning}`);
 if(Object.keys(dependencies).length)console.log('Package dependencies recorded. Use --install or run bun install in the viewer.');
 if(meta.props.some(p=>p.required))console.log('Required props detected: edit preview-props.json or the generated preview.astro wrapper.');
}
main().catch(error=>{console.error(`kuit: ${error.message}`);process.exitCode=1;});
