// Generate portable CSS for standalone HTML demos using the viewer's Tailwind theme.
// Run after changing a demo's utility classes: bun run shader:styles
import { createRequire } from 'node:module';
import { readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const require = createRequire(join(root, 'package.json'));
const { compile } = await import(require.resolve('tailwindcss'));
const theme = await Bun.file(require.resolve('tailwindcss/theme.css')).text();
const globalCSS = await Bun.file(join(root, 'src/styles/global.css')).text();
const tokens = globalCSS.match(/@theme inline\s*\{[^}]+\}/)?.[0];
if (!tokens) throw new Error('Viewer theme tokens are missing');

for (const directory of await readdir(join(root, 'public/shaders'), { withFileTypes: true })) {
  if (!directory.isDirectory()) continue;
  const folder = join(root, 'public/shaders', directory.name);
  const entry = Bun.file(join(folder, 'preview.html'));
  if (!await entry.exists()) continue;
  const html = await entry.text();
  const classes = [...html.matchAll(/class="([^"]+)"/g)].flatMap(match => match[1].split(/\s+/));
  const compiler = await compile(`${theme}\n${tokens}\n@tailwind utilities;`);
  await Bun.write(join(folder, 'preview.css'), `/* Generated by scripts/shader-styles.ts. Edit HTML classes, not this file. */\n${compiler.build(classes)}`);
}
